### ISSUE TITLE
Ensemble training went smoothly but failed in post processing

### ISSUE THREAD

**Issue by Joey-Xue** [fratajcz/speos#2]
Hi, I was using SPEOS on a gene list of my own and the benchmark went well. However when training the ensemble using outercrossvalidation.py I got the following error after the crossvalidation was complete:
`v2run1_outer_4_fold_3 2023-04-06 00:26:29,899 [INFO] speos.experiment: Starting Inference.
Traceback (most recent call last):
  File "/home/zyxue/HMGU_IBD/speos/outer_crossval.py", line 12, in <module>
    pipeline.run()
  File "/home/zyxue/HMGU_IBD/speos/speos/pipeline.py", line 83, in run
    self.postprocessor.run()
  File "/home/zyxue/HMGU_IBD/speos/speos/postprocessing/postprocessor.py", line 51, in run
    self.init_pp_table()
  File "/home/zyxue/HMGU_IBD/speos/speos/postprocessing/postprocessor.py", line 31, in init_pp_table
    unknown_genes, all_genes, positive_genes = self.get_unknown_genes()
  File "/home/zyxue/HMGU_IBD/speos/speos/postprocessing/postprocessor.py", line 818, in get_unknown_genes
    results_path = self.results_paths[0][0]
IndexError: list index out of range
v2run1_outer_4_fold_3 2023-04-06 00:26:30,866 [INFO] speos.experiment: Eval Loss: 0.15703763692735734, Accuracy: 0.923060414207533, Recall: 0.34554973821989526, Precision: 0.04799999999999651, AUROC: 0.7725843700517997, AUPRC: 0.045970491833271426, F1: 0.0842911877394636, MRR: 0.004025395378040788, MR: 4196.136125654451, Target: all
v2run1_outer_4_fold_3 2023-04-06 00:26:30,871 [INFO] speos.experiment: Writing Inference data to ./results/v2run1.h5`

Seems like the results was not properly saved but I don't know why this is happening. The trained model was saved in the inference folder and the logs file look fine.

Here's my config
`model: 
    model: SimpleModel
    architecture: GeneNetwork
    args: []
    kwargs: {}
    pre_mp:
        dim: 50
        n_layers: 2        # resulting number of layers will be n_layers + 1 for the input layer
        act:  elu
    post_mp:
        dim: 50
        n_layers: 2        # resulting number of layers will be n_layers + 2 for the output layer
        act:  elu
    mp: 
        type: gin
        dim: 50
        n_layers: 3
        normalize: instance   # instance, graph, layer
        kwargs: {}

crossval:
  mode: kfold
  n_folds: 4
  positive_only: True
`
Thanks for any help!

**Comment by fratajcz** [comment]
Hi!

Nice hearing from you and to see that everything worked until that point :)

it seems like the culprit is the following line:

```
results_path = self.results_paths[0][0] IndexError: list index out of range
```

The thing is that `self.results_paths` should hold the paths to your results files. The postprocessor finds your results files (those produced by the inference step) by looking in your `config.pp.save_dir` directory for the `tsv` files of the runs. In the default config the `config.inference.save_tsv` is set to `False` to avoid cluttering the directory during benchmark and only write the more compact `h5` files.  Sadly I didnt find the time yet to adapt the postprocessor to the `h5` files, so you'll have to add the following lines to your config:

```

inference:
    save_tsv: True
```

in order for the postprocessing to work. If you inspect the [configs for the ensembles](https://github.com/fratajcz/speos/blob/master/ensemble_configs/config_bm_disorder_gcn.yaml) that I used you will find these lines in every config. I realize that this detail is hard to spot and I will emphasize it in the documentation right away.

Sadly, for this to work you will have to rerun the whole `outer_crossval.py` as I didnt include an inference-only outer cv script, although this might make sense if the problem keeps appearing. Sorry for the inconvencience.

By the way, I see your `n_folds` is set to 4, I'd like to point out that we set it to 10 for the experiments in the paper and numbers as small as 4 are likely to cause unstable results. You can keep it that way for a test run as it is gonna finish way faster but for the final results I'd recommend using an `n_folds` of 10. 

I'm happy to help if anything is unclear and I am very curious about the findings of your benchmark runs :)

Cheers,
Florin

**Comment by Joey-Xue** [comment]
Hi Florin, thanks for the detailed explanation! I was wondering that there should be something wrong with the results saving path but could not figure out why. 
As for the n_folds, since I only have less than 200 genes in my list, setting it to 10 may make the positive labels too sparse, which I believe may also make the model hard to train? I may consider setting it to larger number later. 
The model  did find something interesting, thanks for developing this cool and easy-to-use framework, looking forward to digging deeper into that!
Best,
Zhengyuan
